name: "Active Build Stage"
description: "Build Action for GitHub Action"
author: "Timur Galeev <@timurgaleev>"

branding:
  icon: "box"
  color: "blue"

runs:
  using: docker
  image: docker://timzu/github-actions-build:v0.3.27
